version: '2'
services:
  apache:
    build: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - magento2-sync:/var/www/html:nocopy
      #- ../srcMage2.3.3:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_mode=req remote_port=9007 remote_host=host.docker.internal remote_connect_back=0 idekey=PHPSTORM force_display_errors=1 remote_log=/var/log/xdebug.log"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - magento2-network

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - magento2-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
     - 8080:80
    networks:
      - magento2-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - magento2-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - magento2-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento2-network

networks:
  magento2-network:
    driver: bridge

volumes:
  magento2-sync:
    external: true
  dbdata:
    driver: local